name: Lotto Auto Update
on:
  schedule:
    - cron: '15 12 * * 6' # 한국 시간 매주 토요일 밤 9시 15분 (UTC 12:15)
    - cron: '16 12 * * 6' # 한국 시간 매주 토요일 밤 9시 16분 (UTC 12:15)
    - cron: '17 12 * * 6' # 한국 시간 매주 토요일 밤 9시 17분 (UTC 12:15)
    - cron: '18 12 * * 6' # 한국 시간 매주 토요일 밤 9시 18분 (UTC 12:15)
    - cron: '19 12 * * 6' # 한국 시간 매주 토요일 밤 9시 19분 (UTC 12:15)
    - cron: '20 12 * * 6' # 한국 시간 매주 토요일 밤 9시 20분 (UTC 12:15)
    - cron: '21 12 * * 6' # 한국 시간 매주 토요일 밤 9시 21분 (UTC 12:15)

  workflow_dispatch: # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Update
        run: python update_lotto.py
      - name: Push Changes
        run: |
          git config --global user.name "LottoBot"
          git config --global user.email "bot@github.com"
          git add lotto_data.json
          git commit -m "update data" || exit 0
          git push
